version: '2'
services:

  database:
    build:
      context: ./mark-postgres
      args:
        POSTGRES_USER: myapp
        POSTGRES_PASSWORD: myapp
        POSTGRES_DATABASE: myapp_development
    image: mark-postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql

  app:
    build: ./myapp
    image: myapp
    environment:
      - RAILS_ENV=development
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ~/sandbox/docker-101/myapp:/home/mark/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  database:

#  sandbox:
#     external: true
