version: '2'
services:

  database:
    build: .
    image: mark-postgres
    volumes:
      - postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    network_mode: host

volumes:
 postgresql:

# docker-compose run database
